#!/usr/bin/env bash
#
#  check_reboot_required
# 
#  Nagios Plugin for checking if a system requires a reboot after an
#  upgrade.
#
#  Copyright (c) 2013-2016 Sebastian Nohn <sebastian@nohn.net>.
#  All rights reserved.
# 
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
# 
#   *  Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
# 
#   *  Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in
#      the documentation and/or other materials provided with the
#      distribution.
# 
#   *  Neither the name of Sebastian Nohn nor the names of his
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
# 
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
#  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
#  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
#  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
#  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.

DISTRIBUTOR_ID=$(lsb_release -a 2>&1 | grep "Distributor ID" | awk '{ print $3 }')

function ok {
   echo "OK: no reboot required"
   exit 0
}

function warning {
   echo "WARNING: Package(s) $1 require a reboot"
   exit 1
}

if [ "$DISTRIBUTOR_ID" == "Ubuntu" ] || [ "$DISTRIBUTOR_ID" == "Debian" ] ; then
   if [ ! -f /var/run/reboot-required ]; then
      ok
   else
      warning "$(cat /var/run/reboot-required.pkgs | tr '\n' ' ')"
   fi
else
   # Unknown Distro.
   echo "UNKNOWN distribution $DISTRIBUTOR_ID"
   exit 3
fi

